version: '2'

services:
    lb:
        image: nginx:alpine
        volumes:
            - ./nginx/lb:/etc/nginx/conf.d
        ports:
            - "8080:80"
        environment:
            - TIMEOUT=190
            - DOCKER0NET
        depends_on:
            - varnish1
            - varnish2

    varnish1:
        build: ./varnish
        volumes:
            - ./varnish/front1/default.vcl:/etc/varnish/configs/default.vcl
        ports:
            - "8081:80"
        depends_on:
            - front1

    varnish2:
        build: ./varnish
        volumes:
            - ./varnish/front2/default.vcl:/etc/varnish/configs/default.vcl
        ports:
            - "8082:80"
        depends_on:
            - front2

    back:
        build: ./nginx
        volumes:
            - ./nginx/back:/etc/nginx/conf.d
        volumes_from:
            - backapp
        ports:
            - "443:443"
        environment:
            - FASTCGI_PASS=backapp:9000
            - TIMEOUT=190
            - DOCKER0NET
        depends_on:
            - backapp

    front1:
        image: nginx:alpine
        volumes:
            - ./nginx/front1:/etc/nginx/conf.d
        volumes_from:
            - app1
        ports:
            - "8091:80"
        environment:
            - FASTCGI_PASS=app1:9000
            - TIMEOUT=190
            - DOCKER0NET
        depends_on:
            - app1

    front2:
        image: nginx:alpine
        volumes:
            - ./nginx/front2:/etc/nginx/conf.d
        volumes_from:
            - app2
        ports:
            - "8092:80"
        environment:
            - FASTCGI_PASS=app2:9000
            - TIMEOUT=190
            - DOCKER0NET
        depends_on:
            - app2

    memcached:
        image: memcached:alpine

    backapp:
        build: ./php
        volumes:
            - ./app:/var/www
            - ./app/scripts:/var/www/scripts
            - ./app/var/ezplatform:/var/www/var/ezplatform
            - ./php/logs.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        ports:
            - "9003:9000"
        depends_on:
            - db
            - memcached
        entrypoint: >
            /bin/sh -c "
                if [ ! -d "ezplatform" ]; then
                    php -d memory_limit=-1 /usr/local/bin/composer create-project --prefer-dist --no-interaction ezsystems/ezplatform ezplatform;
                    cp -f scripts/AppKernel.php ezplatform/app/;
                    cp -f scripts/parameters.yml ezplatform/app/config/;
                    cp -f scripts/ezplatform.yml ezplatform/app/config/;
                    cp -f scripts/config.yml ezplatform/app/config/;
                    mkdir -p /var/ezplatform/cache /var/ezplatform/logs;
                    cd ezplatform;
                    php -d memory_limit=-1 app/console ezplatform:install --env prod clean;
                    php -d memory_limit=-1 app/console assets:install --symlink web;
                    php -d memory_limit=-1 app/console assetic:dump --env=dev;
                    chown -R www-data:www-data web /var/ezplatform;
                fi
                /usr/local/sbin/php-fpm
            "
        restart: always

    app1:
        build: ./php
        volumes:
            - ./app:/var/www
            - ./app/var/ezplatform:/var/www/var/ezplatform
            - ./php/logs.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        ports:
            - "9001:9000"
        depends_on:
            - db
            - backapp
            - memcached
        entrypoint: >
            /bin/sh -c "
                if [ ! -d "ezplatform" ]; then
                    mkdir -p /var/ezplatform/cache /var/ezplatform/logs;
                    chown -R www-data:www-data ezplatform/web /var/ezplatform;
                fi
                /usr/local/sbin/php-fpm
            "
        restart: always

    app2:
        build: ./php
        volumes:
            - ./app:/var/www
            - ./app/var/ezplatform:/var/www/var/ezplatform
            - ./php/logs.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        ports:
            - "9002:9000"
        depends_on:
            - db
            - backapp
            - memcached
        entrypoint: >
            /bin/sh -c "
                if [ ! -d "ezplatform" ]; then
                    mkdir -p /var/ezplatform/cache /var/ezplatform/logs;
                    chown -R www-data:www-data ezplatform/web /var/ezplatform;
                fi
                /usr/local/sbin/php-fpm
            "
        restart: always

    db:
        image: mariadb:10.1
        volumes:
            - db_data:/var/lib/mysql
            - ./mysql:/etc/mysql/conf.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ezplatform
            MYSQL_DATABASE: ezplatform
            MYSQL_USER: ezplatform
            MYSQL_PASSWORD: ezplatform

volumes:
    db_data:
